data<-read.csv("household_power_consumption.txt", header=TRUE, na.strings="?",stringsAsFactors=F,sep=";" )
data$Date<-as.Date(data$Date, format="%d/%m/%Y")
newdata<-subset(data, data$Date>="2007-02-01" & data$Date<="2007-02-02")
hist(newdata$Global_active_power, col="Red", xlab="Global Active Power (Killowatts)", ylab="Frequency", main="Global Active Power")
dev.copy(png, file= "plot1.png", height=480, width = 480)
dev.off()